IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [USUARIO] (
    [IDUSUARIO] uniqueidentifier NOT NULL,
    [NOME] nvarchar(150) NOT NULL,
    [EMAIL] nvarchar(50) NOT NULL,
    [SENHA] nvarchar(40) NOT NULL,
    [DATACRIACAO] datetime2 NOT NULL,
    [ATIVO] int NOT NULL,
    CONSTRAINT [PK_USUARIO] PRIMARY KEY ([IDUSUARIO])
);
GO

CREATE UNIQUE INDEX [IX_USUARIO_EMAIL] ON [USUARIO] ([EMAIL]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20230318144703_Initial', N'7.0.4');
GO

COMMIT;
GO

BEGIN TRANSACTION;
GO

CREATE TABLE [CATEGORIA] (
    [IDCATEGORIA] uniqueidentifier NOT NULL,
    [NOME] nvarchar(50) NOT NULL,
    [TIPO] int NOT NULL,
    [IDUSUARIO] uniqueidentifier NOT NULL,
    CONSTRAINT [PK_CATEGORIA] PRIMARY KEY ([IDCATEGORIA]),
    CONSTRAINT [FK_CATEGORIA_USUARIO_IDUSUARIO] FOREIGN KEY ([IDUSUARIO]) REFERENCES [USUARIO] ([IDUSUARIO])
);
GO

CREATE TABLE [CONTA] (
    [IDCONTA] uniqueidentifier NOT NULL,
    [NOME] nvarchar(100) NOT NULL,
    [DESCRICAO] nvarchar(250) NOT NULL,
    [DATA] date NOT NULL,
    [VALOR] decimal(18,2) NOT NULL,
    [IDUSUARIO] uniqueidentifier NOT NULL,
    [IDCATEGORIA] uniqueidentifier NOT NULL,
    CONSTRAINT [PK_CONTA] PRIMARY KEY ([IDCONTA]),
    CONSTRAINT [FK_CONTA_CATEGORIA_IDCATEGORIA] FOREIGN KEY ([IDCATEGORIA]) REFERENCES [CATEGORIA] ([IDCATEGORIA]),
    CONSTRAINT [FK_CONTA_USUARIO_IDUSUARIO] FOREIGN KEY ([IDUSUARIO]) REFERENCES [USUARIO] ([IDUSUARIO])
);
GO

CREATE INDEX [IX_CATEGORIA_IDUSUARIO] ON [CATEGORIA] ([IDUSUARIO]);
GO

CREATE INDEX [IX_CONTA_IDCATEGORIA] ON [CONTA] ([IDCATEGORIA]);
GO

CREATE INDEX [IX_CONTA_IDUSUARIO] ON [CONTA] ([IDUSUARIO]);
GO

INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
VALUES (N'20230318160628_AddCategoriaAndConta', N'7.0.4');
GO

COMMIT;
GO

